"""Added Profession to User link

Revision ID: ff88358d9f7e
Revises: 32d21798b475
Create Date: 2023-04-07 03:02:43.672796

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'ff88358d9f7e'
down_revision = '32d21798b475'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profession_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'profession', ['profession_id'], ['id'])
    op.drop_column('user', 'profession')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profession', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'profession_id')
    # ### end Alembic commands ###
